import Head from "next/head";
import axios from "axios";
// import { Inter } from "@next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // axios.get("localhost:1337/api/quizzes").then((res) => {
  //   console.log(res);
  // });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>hi</div>
    </>
  );
}
